# Generated by Django 5.1 on 2024-08-28 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='galleries/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(choices=[('cake', 'Cake'), ('teacup', 'Teacup'), ('teapot', 'Teapot'), ('egg', 'Egg'), ('steak', 'Steak'), ('hamburger', 'Hamburger'), ('hotdog', 'Hotdog'), ('pizza', 'Pizza'), ('sausage', 'Sausage'), ('chicken', 'Chicken'), ('fish', 'Fish'), ('carrot', 'Carrot'), ('cheese', 'Cheese'), ('bread', 'Bread'), ('ice-cream', 'Ice cream'), ('candy', 'Candy'), ('lollipop', 'Lollipop'), ('coffee-bean', 'Coffee bean'), ('coffee-cup', 'A cup of coffee'), ('cherry', 'Cherry'), ('grapes', 'Grapes'), ('citrus', 'Citrus'), ('apple', 'Apple'), ('leaf', 'Leaf')], max_length=100),
        ),
    ]
