# Generated by Django 5.1 on 2024-09-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_block_remove_review_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='css_class',
            field=models.CharField(default='wow', max_length=200),
        ),
    ]
