# Generated by Django 5.1 on 2024-09-01 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_block_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='css_col_class',
            field=models.CharField(default='col-sm-4', max_length=200),
        ),
    ]
