# Generated by Django 5.1 on 2024-09-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_block_css_col_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('dine-in', 'Dine-In'), ('carry-out', 'Carry-Out'), ('event-catering', 'Event Catering')], max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
