# Generated by Django 4.2.15 on 2024-09-25 18:42

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название шаблона')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержание письма (HTML)')),
            ],
        ),
    ]
