# Generated by Django 4.2.15 on 2024-10-09 10:34

from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_emailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='blocks/')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text (HTML)')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text (HTML)'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Template'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Theme of the letter'),
        ),
    ]
