# Generated by Django 4.2.15 on 2024-10-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_aboutus_alter_emailtemplate_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='teams/')),
                ('link_facebook', models.URLField(blank=True, null=True)),
                ('link_twitter', models.URLField(blank=True, null=True)),
                ('link_instagram', models.URLField(blank=True, null=True)),
                ('link_google_plus', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
